### ISSUE TITLE
Mod loading issue

### ISSUE THREAD

**Issue by Efimero** [EnderiumSmith/CharcoalPit#30] opened 2017-12-02 20:50 UTC
The mod is loading with wrong localization names/wrong textures. The blocks work, but look wrong.
Those in the image should be the Charcoal Pit blocks, but show up in jei like that.
Forge version: 2556
Minecraft: 1.12.2
Charcoal Pit: [1.12] 1.7

![image](https://user-images.githubusercontent.com/300735/33519593-fd5fd94a-d7a9-11e7-88b1-ec770562db7d.png)

**Comment by EnderiumSmith** [comment] 2017-12-04 14:17
duplicate of #29. its fixed but i broke something else and need to fix it before i release the next version. Charcoal Pit needs to load first.

**Closed** 2017-12-04 15:18 UTC
